config/routes.rb
DemoTaskApp::Application.routes.draw do

  resources :users

  resources :tasks
  root to: "static_pages#show"
  match "/open", to: "tasks#open"
  match "/done", to: "tasks#done"
  match "/toggle/status", to: "tasks#toggleStatus"
  match "/download", to: "tasks#download"

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  description :string(255)
#  priority    :integer
#  deadline    :datetime
#  reminder    :datetime
#  status      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Task < ActiveRecord::Base
  attr_accessible :deadline, :description, :priority, :reminder, :status

  after_initialize :init
  after_create :reminder_email

@@REMINDER_TIME = 30.minutes
  validates :priority, :inclusion => { :in => 1..5, :message => "The priority must be between 1 and 5" }, presence: true
  validates :status, :inclusion => { :in => 1..3, :message => "The status must be between 1 and 3" } , presence: true
  validates :description , presence: true
  validates :deadline , presence: true

  def init
  	self.status = 1
  end
   # before_save { deadline.to_datetime! ; reminder.to_datetime! }
def self.as_csv
  CSV.generate do |csv|
    csv << column_names
    all.each do |item|
      csv << item.attributes.values_at(*column_names)
    end
  end
end
def reminder_email
	ExampleMailer.sample_email(description).deliver
end

 def when_to_run
    reminder
  end

  handle_asynchronously :reminder_email , :run_at => Proc.new { |i| i.when_to_run }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
  end

  def help
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def home
  end

  def help
  end

  def new
  	@task=Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(params[:task])
    if @task.save
    	redirect_to @task
      # Handle a successful save.
    else
      render 'new'
    end
  end

  def index
     @tasks = Task.paginate(page: params[:page])
  end

  def open
   	 @tasks = Task.order(params[:sort]).where(status: 1).paginate(page: params[:page])
  end
   
  def done
   	 @tasks = Task.where(status: 2).paginate(page: params[:page])
  end

  def toggleStatus
   	@task = Task.find(params[:id])
   	@task.status = params[:status]
   	 if @task.save
    	redirect_to @task
      # Handle a successful save.
    else
      render 'new'
    end
  end

  def download
	  @tasks = Task.order(:deadline)
	  respond_to do |format|
	  format.html
	  format.csv { send_data @tasks.as_csv }
	  format.xml { send_data @tasks.to_xml }
  end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by Krishnanand
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Tasks app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Open Tasks!",    open_path %></li>
          <li><%= link_to "Done Tasks :-)",    done_path %></li>
           <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Settings <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Add Email", new_user_path %></li>
                <li><%= link_to "Show subscribers", users_path %></li>
                <li><%= link_to "Download", download_path %></li>
                <li class="divider"></li>
              </ul>
            </li>
          <li><%= link_to "Help",    '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
       <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@task.errors.count, "error") %>.
    </div>
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/show.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Tasks App</h1>

  <h2>
    This is the home page for the
    taks application.
  </h2>

  <%= link_to "Create tasks!", new_task_path, class: "btn btn-large btn-primary" %>
</div>

app/views/tasks/_task.html.erb
<li>
  <%= link_to task.description, task %>
  | <%= task.priority %>
  | <%= task.deadline %>
   | <%= link_to "Mark done", toggle_status_path(:id=> task.id, :status=> 2) %>
</li>

app/views/tasks/done.html.erb
<% provide(:title, 'All tasks') %>
<h1>All done tasks</h1>

<%= will_paginate %>
<ul class="tasks">
 <% @tasks.each do |task| %>
    <li>
      <%= link_to task.description, task %>
      | <%= link_to "Re-open", toggle_status_path(:id=> task.id, :status=> 1) %>
      | <%= link_to "Archive", toggle_status_path(:id=> task.id, :status=> 3) %>
    </li>
  <% end %>

<%= will_paginate %>

app/views/tasks/download.html.erb
<p>
  Download:
  <%= link_to "CSV", download_path(format: "csv") %> |
  <%= link_to "XML", download_path(format: "xml") %>
</p>

app/views/tasks/help.html.erb
<h1>Tasks#help</h1>
<p>Find me in app/views/tasks/help.html.erb</p>

app/views/tasks/index.html.erb
<% provide(:title, 'All tasks') %>
<h1>All open tasks</h1>

<%= will_paginate %>
<ul class="tasks">
  <%= render @tasks %>
</ul>

<%= will_paginate %>

app/views/tasks/new.html.erb
<% provide(:title, 'Create task') %>
<h1>Create Task</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@task) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.label :priority %>
      <%= f.select :priority, ['1', '2','3','4','5']%>
<!-- 
      <%= f.label :status %>
      <%= f.text_field :status %> -->

      <%= f.label :deadline %>
      <%= f.date_select :deadline %>

      <%= f.label :reminder %>
      <%= f.datetime_select :reminder %>

      <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tasks/open.html.erb
<% provide(:title, 'All tasks') %>
<h1>All open tasks</h1>
<%= will_paginate %>
<table class="table table-striped">
  <tr>
    <th><%= link_to "Description", open_path(:sort => "description" )%></th>
    <th><%= link_to "deadline" , open_path( :sort => "deadline") %></th>
    <th><%= link_to "priority" , open_path(:sort => "priority" ) %></th>
  </tr>
  <% for task in @tasks %>
  <tr>
    <td><%= task.description %></td>
    <td><%= task.deadline %></td>
    <td><%= task.priority %></td>
    <td> <%= link_to "Mark done", toggle_status_path(:id=> task.id, :status=> 2) %> </td>
  </tr>
  <% end %>
</table>

<%= will_paginate %>

app/views/tasks/show.html.erb
<%= @task.description  %>, <%= @task.id %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>